export const customer: any[] = [
  { id: 1, name: "Advanced Optical Components", code: "C0001" },
  { id: 2, name: "Action Manufacturing Company", code: "C0002" },
  { id: 3, name: "Acumentrics Corporation", code: "C0003" },
  { id: 4, name: "Adeptron Technologies Corp.", code: "C0004" },
  { id: 5, name: "All Flex Inc.", code: "C0005" },
  { id: 6, name: "Applanix Corporation", code: "C0006" },
  { id: 7, name: "American Technologies, LLC", code: "C0007" },
  { id: 8, name: "Advanced Process Technology", code: "C0008" },
  { id: 9, name: "Ault Incorporated", code: "C0009" },
  { id: 10, name: "Authentix", code: "C0010" },
  { id: 11, name: "Axela Biosensors Inc.", code: "C0011" },
  { id: 12, name: "Banta Global Turnkey", code: "C0012" },
  { id: 13, name: "Bose Corporation", code: "C0013" },
  { id: 14, name: "Bioscrypt Inc.", code: "C0014" },
  { id: 15, name: "Bisco Industries, Inc.", code: "C0015" },
  { id: 16, name: "BreconRidge Corp.", code: "C0016" },
  { id: 17, name: "Buskro, Ltd", code: "C0017" },
  { id: 18, name: "CRI, Inc.", code: "C0018" },
  { id: 19, name: "Cadcopac Inc.", code: "C0019" },
  { id: 20, name: "Canadian Source Corporation", code: "C0020" },
  { id: 21, name: "Cardiovascular Diagnostics Inc", code: "C0021" },
  { id: 22, name: "Chorum Technologies L.P.", code: "C0022" },
  { id: 23, name: "Circuit CAD Corporation", code: "C0023" },
  { id: 24, name: "SAE POWER (Colm Campbell )", code: "C0024" },
  { id: 25, name: "Creation Technologies Inc.", code: "C0025" },
];
