export const panasonic: any[] = [
  {
    id: 1,
    material: "FLP 09/12.5/09",
    price: 17.33,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 2,
    material: "FLP 09/20/09",
    price: 11.55,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 3,
    material: "FLP 09/25/09(FLP7163)",
    price: 11.55,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 4,
    material: "FLP 09/50/09",
    price: 14.3,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 5,
    material: "FLP 12/12.5/12",
    price: 9.9,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 6,
    material: "FLP 12/20/12",
    price: 7.43,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 7,
    material: "FLP 12/25/12 (FLP7164)",
    price: 7.43,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 8,
    material: "FLP 12/50/12 (FLP7319) RA",
    price: 11,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 9,
    material: "FLP 12/75/12",
    price: 16.5,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 10,
    material: "FLP 18/100/18 (FLP8545)",
    price: 19.25,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 11,
    material: "FLP 18/12.5/18",
    price: 9.9,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 12,
    material: "FLP 18/125/18 (FLP8555)",
    price: 23.1,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 13,
    material: "FLP 18/150/18 (FLP8565)",
    price: 28.6,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 14,
    material: "FLP 18/20/18",
    price: 6.88,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 15,
    material: "FLP 18/25/18 (FLP8515)",
    price: 6.38,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 16,
    material: "FLP 18/50/18 (FLP8525)",
    price: 7.65,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 17,
    material: "FLP 18/75/18 (FLP8535)",
    price: 16.5,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 18,
    material: "FLP 35/100/35 (FLP9141)",
    price: 21.56,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 19,
    material: "FLP 35/12.5/35",
    price: 11.28,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 20,
    material: "FLP 35/125/35 (FLP9151)",
    price: 24.2,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 21,
    material: "FLP 35/150/35 (FLP9161)",
    price: 30.25,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 22,
    material: "FLP 35/20/35",
    price: 7.1,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 23,
    material: "FLP 35/25/35 (FLP9111)",
    price: 7.26,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 24,
    material: "FLP 35/50/35 (FLP9121)",
    price: 7.65,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 25,
    material: "FLP 35/75/35 (FLP9131)",
    price: 18.7,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 26,
    material: "FLP 70/100/70",
    price: 25.3,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 27,
    material: "FLP 70/125/70",
    price: 28.6,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 28,
    material: "FLP 70/150/70",
    price: 33,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 29,
    material: "FLP 70/25/70",
    price: 12.65,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 30,
    material: "FLP 70/50/70 (FLP9222)",
    price: 14.08,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 31,
    material: "FLP 70/75/70",
    price: 22,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 32,
    material: "RF-606 25um",
    price: 4.4,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 33,
    material: "RF-606 50um",
    price: 5.23,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 34,
    material: "R-F705T 1210012/RA",
    price: 22,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 35,
    material: "R-F705T 122512/RA",
    price: 17.05,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 36,
    material: "R-F705T 125012/RA",
    price: 16.5,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 37,
    material: "R-F705T 127512/RA",
    price: 19.8,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 38,
    material: "R-F705T 1810018/RA",
    price: 22,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 39,
    material: "R-F705T 182518/RA",
    price: 17.05,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 40,
    material: "R-F705T 185018/RA",
    price: 16.5,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 41,
    material: "R-F705T 187518/RA",
    price: 19.8,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 42,
    material: "R-MB17 Bond Sheet+B3:Q48",
    price: 6.05,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
  {
    id: 43,
    material: "FLP125012(7125)ED   ",
    price: 7.5,
    supplier: "Panasonic",
    formula: "size * exchange * cost",
  },
];
