import { jsonMap } from "Library/Types";

export const dupont: jsonMap[] = [
  {
    id: 1,
    material: "AC121200R",
    price: 7.39,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 2,
    material: "AC 182500",
    price: 9.02,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 3,
    material: "AC3525",
    price: 7.99,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 4,
    material: "AP7391",
    price: 19.1,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 5,
    material: "AP7421",
    price: 40.09,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 6,
    material: "AP7434R",
    price: 21.26,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 7,
    material: "AP8515R",
    price: 10.38,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 8,
    material: "AP8525R",
    price: 9.08,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 9,
    material: "AP8535R",
    price: 17.99,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 10,
    material: "AP8545R",
    price: 23.08,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 11,
    material: "AP8555",
    price: 40.22,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 12,
    material: "AP9111R",
    price: 8.8,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 13,
    material: "AP9121R",
    price: 9.67,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 14,
    material: "AP9131R",
    price: 16.12,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 15,
    material: "AP9141R",
    price: 20.37,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 16,
    material: "AP9151R",
    price: 42.81,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 17,
    material: "AP9161R",
    price: 46.85,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 18,
    material: "AP9212R",
    price: 11.54,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 19,
    material: "AP9222R",
    price: 12.14,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 20,
    material: "AP9232R",
    price: 16.97,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 21,
    material: "AP9242R",
    price: 21.17,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 22,
    material: "AP9252R",
    price: 61.69,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 23,
    material: "FR0100",
    price: 1.44,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 24,
    material: "FR0110",
    price: 1.71,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 25,
    material: "FR0111",
    price: 2.68,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 26,
    material: "FR0120",
    price: 2.55,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 27,
    material: "FR0121",
    price: 3.29,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 28,
    material: "FR0130",
    price: 3.52,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 29,
    material: "FR0131",
    price: 4.29,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 30,
    material: "FR0150",
    price: 5.5,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 31,
    material: "FR0200",
    price: 1.84,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 32,
    material: "FR0210",
    price: 2.53,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 33,
    material: "FR0212",
    price: 4.73,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 34,
    material: "FR0220",
    price: 3.13,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 35,
    material: "FR0230",
    price: 4.49,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 36,
    material: "FR0250",
    price: 6.41,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 37,
    material: "FR0310",
    price: 3.28,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 38,
    material: "FR1500R",
    price: 4.87,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 39,
    material: "FR7001",
    price: 3.68,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 40,
    material: "FR7013",
    price: 4.05,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 41,
    material: "FR7021",
    price: 9.59,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 42,
    material: "FR8510R",
    price: 4.05,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 43,
    material: "FR8515R",
    price: 6.62,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 44,
    material: "FR8520R",
    price: 5.15,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 45,
    material: "FR8525R",
    price: 7.82,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 46,
    material: "FR8535R",
    price: 22,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 47,
    material: "FR9110R",
    price: 3.16,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 48,
    material: "FR9111R",
    price: 5.39,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 49,
    material: "FR9120R",
    price: 4.13,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 50,
    material: "FR9121R",
    price: 6.06,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 51,
    material: "FR9130R",
    price: 9.82,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 52,
    material: "FR9131R",
    price: 15.22,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 53,
    material: "FR9150R",
    price: 7.05,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 54,
    material: "FR9210R",
    price: 3.81,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 55,
    material: "FR9212R",
    price: 6.47,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 56,
    material: "FR9220R",
    price: 4.9,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 57,
    material: "FR9222R",
    price: 7.43,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 58,
    material: "LF0100",
    price: 3.2,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 59,
    material: "LF0110",
    price: 3.04,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 60,
    material: "LF0111",
    price: 3.92,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 61,
    material: "LF0120",
    price: 3.79,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 62,
    material: "LF0121",
    price: 4.57,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 63,
    material: "LF0130",
    price: 4.21,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 64,
    material: "LF0131",
    price: 5.36,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 65,
    material: "LF0150",
    price: 6.07,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 66,
    material: "LF0200",
    price: 3.01,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 67,
    material: "LF0210",
    price: 3.64,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 68,
    material: "LF0212",
    price: 7.39,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 69,
    material: "LF0220",
    price: 4.43,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 70,
    material: "LF0230",
    price: 5.65,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 71,
    material: "LF0250",
    price: 6.58,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 72,
    material: "LF0310",
    price: 4.23,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 73,
    material: "LF7001",
    price: 8.21,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 74,
    material: "LF7013",
    price: 8.95,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 75,
    material: "LF8510R",
    price: 9.34,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 76,
    material: "LF8515R",
    price: 10.06,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 77,
    material: "LF8520R",
    price: 10.42,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 78,
    material: "LF8525R",
    price: 10.49,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 79,
    material: "LF8530R",
    price: 10.8,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 80,
    material: "LF8535R",
    price: 13.28,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 81,
    material: "LF8550R",
    price: 16.23,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 82,
    material: "LF8555R",
    price: 20.05,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 83,
    material: "LF9110R",
    price: 4.9,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 84,
    material: "LF9111R",
    price: 6.78,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 85,
    material: "LF9120R",
    price: 5.86,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 86,
    material: "LF9121R",
    price: 8.02,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 87,
    material: "LF9130R",
    price: 6.62,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 88,
    material: "LF9131R",
    price: 9.27,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 89,
    material: "LF9150R",
    price: 9.68,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 90,
    material: "LF9210R",
    price: 5.64,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 91,
    material: "LF9212R",
    price: 8.59,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 92,
    material: "LF9220R",
    price: 6.89,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 93,
    material: "LF9222R",
    price: 9.68,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 94,
    material: "TK 3610036 ",
    price: 45.85,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 95,
    material: "TK 1810018",
    price: 48.48,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
  {
    id: 96,
    material: "LF-B 0110  ",
    price: 12.52,
    supplier: "Dupont",
    formula: "size * exchange * cost * freight",
  },
];
