import { jsonMap } from "Library/Types";

export const cover: jsonMap[] = [
  {
    id: 1,
    material: "FR0110",
    price: 1.5998,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 2,
    material: "FR0120",
    price: 2.3576,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 3,
    material: "FR0130",
    price: 3.252225,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 4,
    material: "FR0150",
    price: 5.07305,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 5,
    material: "FR0210",
    price: 2.33655,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 6,
    material: "FR0220",
    price: 3.125925,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 7,
    material: "FR0230",
    price: 4.14685,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 8,
    material: "FR0250",
    price: 5.91505,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 9,
    material: "FR0310",
    price: 3.0312,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 10,
    material: "FR7001",
    price: 3.399575,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 11,
    material: "FR7013",
    price: 3.736375,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 12,
    material: "LF0110",
    price: 3.041725,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 13,
    material: "LF0120",
    price: 3.789,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 14,
    material: "LF0130",
    price: 4.21,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 15,
    material: "LF0150",
    price: 6.072925,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 16,
    material: "LF0210",
    price: 3.64165,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 17,
    material: "LF0220",
    price: 4.431025,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 18,
    material: "LF0230",
    price: 5.651925,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 19,
    material: "LF0250",
    price: 6.578125,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 20,
    material: "LF0310",
    price: 4.23105,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 21,
    material: "LF7001",
    price: 8.2095,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 22,
    material: "LF7013",
    price: 8.94625,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 1400,
    material: "FR4 .006 H/H Black stiffener",
    price: 8.82,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 1500,
    material: "FR4 .008 H/H Black stiffener",
    price: 8.78,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 1600,
    material: "FR4 .015 H/H Black stiffener",
    price: 4.47,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 1700,
    material: "FR4 .020 Black stiffener (Crimson Trace)",
    price: 5.3,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 1800,
    material: "SPC 15A/12A",
    price: 13.48,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 2100,
    material: "AL Foil .002",
    price: 30.21,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 2200,
    material: "AL Foil .006",
    price: 33.89,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 2300,
    material: "AL Foil .008",
    price: 10.8,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 2400,
    material: "R-F705S 1810018 (LCP)",
    price: 18,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 2500,
    material: "R-F705S 185018 (LCP)",
    price: 13,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 2900,
    material: "Desiccant",
    price: 0.11,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 3000,
    material: "HIC card",
    price: 0.19,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 3100,
    material: "TATSUTA PC5900 or PC5600",
    price: 6.5,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 3200,
    material: "CONFORMAL COATING",
    price: 4,
    formula: "exchange * price * amount",
    supplier: "-",
    amount: 0,
  },
  {
    id: 3123,
    material: "51N 1080 prepreg",
    price: 1.72,
    supplier: "-",
    amount: 0,
    formula: "price * amount * exchange * 1.06",
  },
  {
    id: 4123,
    material: "51N 106 prepreg",
    price: 2.02,
    supplier: "-",
    amount: 0,
    formula: "price * amount * exchange * 1.06",
  },
  {
    id: 5123,
    material: "37N 1080 prepreg",
    price: 3.44,
    supplier: "-",
    amount: 0,
    formula: "price * amount * exchange * 1.06",
  },
  {
    id: 6123,
    material: "37N 106 prepreg",
    price: 3.44,
    supplier: "-",
    amount: 0,
    formula: "price * amount * exchange * 1.06",
  },
  {
    id: 8123,
    material: "1/2 oz. CU",
    price: 4,
    supplier: "-",
    amount: 0,
    formula: "price * amount * exchange * 1.06",
  },
  {
    id: 9123,
    material: "COPPER RA 1 oz. STD",
    price: 2.38,
    supplier: "-",
    amount: 0,
    formula: "price * amount * exchange * 1.06",
  },
  {
    id: 10123,
    material: "COPPER RA 2 oz. STD",
    price: 4.33,
    supplier: "-",
    amount: 0,
    formula: "price * amount * exchange * 1.06",
  },
  {
    id: 11123,
    material: "7OZ or .010 RA CU",
    price: 5.38,
    supplier: "-",
    amount: 0,
    formula: "price * amount * exchange * 1.06",
  },
];
