import { jsonMap } from "Interface/Types";

export const dryFilm: jsonMap[] = [
  {
    id: 1,
    price: 0.22,
    material: "DRY FILM",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 2,
    price: 0.78,
    material: "DRY FILM GOLD",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 3,
    price: 4.71,
    material: "PRESS ",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 4,
    price: 8,
    material: "DRILL",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 5,
    price: 100,
    material: "LASER DRILL",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 6,
    price: 100,
    material: "LASER TOP COVERLAY",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 7,
    price: 100,
    material: "LASER BOTTOM COVERLAY",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 8,
    price: 100,
    material: "LASER MINIPANEL",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 9,
    price: 100,
    material: "LASER FLEX OUTLINE",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 10,
    price: 11.27,
    material: "PTH",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 11,
    price: 8.25,
    material: "PLASMA",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 12,
    price: 0.51,
    material: "SOLDERMASK",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 13,
    price: 2.5,
    material: "SILKSCREEN ",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 14,
    price: 10,
    material: "ROUTE 10",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 15,
    price: 25,
    material: "ROUTE 25",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 16,
    price: 0.58,
    material: "SILVER SHIELD",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 17,
    price: 1.24,
    material: "SILVER",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 18,
    price: 3,
    material: "AgCl",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 19,
    price: 17.65,
    material: "HASL (Hot air solder leveling)",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 20,
    price: 70,
    material: "HARD GOLD",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 21,
    price: 17,
    material: "ENIG (Electroless nickel immersion gold )",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 22,
    price: 85,
    material: "ENEPIG (nickel/electroless palladium/gold ) - 12x18",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 23,
    price: 17.5,
    material: "TEST (17.5)",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 24,
    price: 23,
    material: "TEST (23)",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 25,
    price: 34.5,
    material: "TEST (34.5)",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 26,
    price: 5,
    material: "SILVER LABOUR",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 27,
    price: 40.5,
    material: "VIA FILL - 12x18",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 28,
    price: 77.76,
    material: "VIA FILL - 18x24",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 29,
    price: 15,
    material: "SCORE (15)",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 30,
    price: 25,
    material: "SCORE (25)",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 31,
    price: 75,
    material: "SCORE (75)",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 32,
    price: 100,
    material: "SCORE (100)",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 33,
    price: 40,
    material: "LABOUR (40)",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 34,
    price: 60,
    material: "LABOUR (60)",
    formula: "cost * exchange",
    supplier: "-",
  },
  {
    id: 35,
    price: 80,
    material: "LABOUR (80)",
    formula: "cost * exchange",
    supplier: "-",
  },
];

export const stiffener: jsonMap[] = [
  {
    id: 1,
    material: "3M 9460 (PSA)",
    price: 2.8,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 2,
    material: "3M9085",
    price: 3.05,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 3,
    material: "3M 467 MP (PSA)",
    price: 1.8,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 4,
    material: "3M 468",
    price: 2,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 5,
    material: "3M 9469",
    price: 4.17,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 6,
    material: "3M9445",
    price: 2.78,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 7,
    material: "3M 966",
    price: 1.39,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 8,
    material: "3M 9703",
    price: 0,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 9,
    material: "3M9743",
    price: 7.73,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 10,
    material: "3M 460EG Eccobond",
    price: 22.35,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 11,
    material: "Taiflex Black /FHB0515 (0.5 mil film, 15um adhesive)",
    price: 2.83,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 12,
    material: "Taiflex Black /FHB 1025 (1mil film, 1mil adhesive)",
    price: 2.14,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 13,
    material: "Taiflex White /FHW1025",
    price: 2.71,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 14,
    material: "FR4 .006 H/H Black stiffener",
    price: 8.82,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 15,
    material: "FR4 .008 H/H Black stiffener",
    price: 8.78,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 16,
    material: "FR4 .015 H/H Black stiffener",
    price: 4.47,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 17,
    material: "FR4 .020 Black stiffener (Crimson Trace)",
    price: 5.3,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 18,
    material: "SPC 15A/12A",
    price: 13.48,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 19,
    material: "Arisawa C23 0515",
    price: 5.01,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 20,
    material: "Arisawa C23 0525",
    price: 5.18,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 21,
    material: "AL Foil .002",
    price: 30.21,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 22,
    material: "AL Foil .006",
    price: 33.89,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 23,
    material: "AL Foil .008",
    price: 10.8,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 24,
    material: "R-F705S 1810018 (LCP)",
    price: 18,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 25,
    material: "R-F705S 185018 (LCP)",
    price: 13,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 26,
    material: "DuPont Pyralux TK Clad  TK 1815018 (Mechanical routing)",
    price: 27.12,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 27,
    material: "DuPont Pyralux TK Clad  TK 1810018 (Mechanical routing)",
    price: 48.12,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 28,
    material: "DuPont Pyralux TK Clad  TK3610036R (Mechanical routing)",
    price: 43.25,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 29,
    material: "Desiccant",
    price: 0.11,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 30,
    material: "HIC card",
    price: 0.19,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 31,
    material: "TATSUTA PC5900 or PC5600",
    price: 6.5,
    formula: "exchange * cost * size",
    supplier: "-",
  },
  {
    id: 32,
    material: "CONFORMAL COATING",
    price: 4,
    formula: "exchange * cost * size",
    supplier: "-",
  },
];
