import { jsonMap } from "Library/Types";

export const cover: jsonMap[] = [
  {
    id: 1,
    material: "FR0110",
    price: 1.5998,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 2,
    material: "FR0120",
    price: 2.3576,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 3,
    material: "FR0130",
    price: 3.252225,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 4,
    material: "FR0150",
    price: 5.07305,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 5,
    material: "FR0210",
    price: 2.33655,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 6,
    material: "FR0220",
    price: 3.125925,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 7,
    material: "FR0230",
    price: 4.14685,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 8,
    material: "FR0250",
    price: 5.91505,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 9,
    material: "FR0310",
    price: 3.0312,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 10,
    material: "FR7001",
    price: 3.399575,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 11,
    material: "FR7013",
    price: 3.736375,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 12,
    material: "LF0110",
    price: 3.041725,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 13,
    material: "LF0120",
    price: 3.789,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 14,
    material: "LF0130",
    price: 4.21,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 15,
    material: "LF0150",
    price: 6.072925,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 16,
    material: "LF0210",
    price: 3.64165,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 17,
    material: "LF0220",
    price: 4.431025,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 18,
    material: "LF0230",
    price: 5.651925,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 19,
    material: "LF0250",
    price: 6.578125,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 20,
    material: "LF0310",
    price: 4.23105,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 21,
    material: "LF7001",
    price: 8.2095,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 22,
    material: "LF7013",
    price: 8.94625,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 100,
    material: "3M 9460 (PSA)",
    price: 2.8,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 200,
    material: "3M9085",
    price: 3.05,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 300,
    material: "3M 467 MP (PSA)",
    price: 1.8,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 400,
    material: "3M 468",
    price: 2,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 500,
    material: "3M 9469",
    price: 4.17,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 600,
    material: "3M9445",
    price: 2.78,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 700,
    material: "3M 966",
    price: 1.39,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 800,
    material: "3M 9703",
    price: 0,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 900,
    material: "3M9743",
    price: 7.73,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 1000,
    material: "3M 460EG Eccobond",
    price: 22.35,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 1100,
    material: "Taiflex Black /FHB0515 (0.5 mil film, 15um adhesive)",
    price: 2.83,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 1200,
    material: "Taiflex Black /FHB 1025 (1mil film, 1mil adhesive)",
    price: 2.14,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 1300,
    material: "Taiflex White /FHW1025",
    price: 2.71,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 1400,
    material: "FR4 .006 H/H Black stiffener",
    price: 8.82,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 1500,
    material: "FR4 .008 H/H Black stiffener",
    price: 8.78,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 1600,
    material: "FR4 .015 H/H Black stiffener",
    price: 4.47,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 1700,
    material: "FR4 .020 Black stiffener (Crimson Trace)",
    price: 5.3,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 1800,
    material: "SPC 15A/12A",
    price: 13.48,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 1900,
    material: "Arisawa C23 0515",
    price: 5.01,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 2000,
    material: "Arisawa C23 0525",
    price: 5.18,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 2100,
    material: "AL Foil .002",
    price: 30.21,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 2200,
    material: "AL Foil .006",
    price: 33.89,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 2300,
    material: "AL Foil .008",
    price: 10.8,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 2400,
    material: "R-F705S 1810018 (LCP)",
    price: 18,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 2500,
    material: "R-F705S 185018 (LCP)",
    price: 13,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 2600,
    material: "DuPont Pyralux TK Clad  TK 1815018 (Mechanical routing)",
    price: 27.12,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 2700,
    material: "DuPont Pyralux TK Clad  TK 1810018 (Mechanical routing)",
    price: 48.12,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 2800,
    material: "DuPont Pyralux TK Clad  TK3610036R (Mechanical routing)",
    price: 43.25,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 2900,
    material: "Desiccant",
    price: 0.11,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 3000,
    material: "HIC card",
    price: 0.19,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 3100,
    material: "TATSUTA PC5900 or PC5600",
    price: 6.5,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
  {
    id: 3200,
    material: "CONFORMAL COATING",
    price: 4,
    formula: "size * exchange * cost * freight",
    supplier: "-",
  },
];
