export const NREDatabase = [
  {
    id: 1,
    material: "Photo Tools",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 2,
    material: "Electrical Test",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 3,
    material: "Outline Die",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 4,
    material: "Secondary Test Fixture",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 5,
    material: "Assyembly Stencils",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 6,
    material: "Assembly Pallets",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 7,
    material: "Design Charge",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 8,
    material: "Production Tooling",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  { id: 9, material: "Hasl", price: 0, amount: 0, formula: "price * amount" },
];
