export const NREDatabase = [
  {
    id: 1,
    service: "Photo Tools",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 2,
    service: "Electrical Test",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 3,
    service: "Outline Die",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 4,
    service: "Secondary Test Fixture",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 5,
    service: "Assyembly Stencils",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 6,
    service: "Assembly Pallets",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 7,
    service: "Design Charge",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 8,
    service: "Production Tooling",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  { id: 9, service: "Hasl", price: 0, amount: 0, formula: "price * amount" },
];
