import { jsonMap } from "Library/Types";

export const dryFilm = [
  {
    id: 1,
    price: 0.25,
    material: "DRY FILM",
    formula: "price * amount * exchange * 1.2 * size",
    amount: 0,
  },
  {
    id: 2,
    price: 0.86,
    material: "DRY FILM GOLD",
    formula: "price * amount * exchange * 1.2 * size",
    amount: 0,
  },
  {
    id: 3,
    price: 0.56,
    material: "S/M Film",
    formula: "price * amount * exchange * 1.2 * size * 1.06",
    amount: 0,
  },
  {
    id: 4,
    price: 4.71,
    material: "PRESS",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 5,
    price: 10,
    material: "DRILL",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 6,
    price: 100,
    material: "LASER DRILL",
    formula: "price * amount * 1.19",
    amount: 0,
  },
  {
    id: 7,
    price: 12.4,
    material: "PTH",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 8,
    price: 8.86,
    material: "ETCH",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 9,
    price: 12.98,
    material: "Single Sided Etch 12 x 18 panel",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 10,
    price: 15.4,
    material: "Single Sided Etch 18 x 24 panel",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 101,
    price: 15.52,
    material: "Double sided etch 12 x 18 panel",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 11,
    price: 20.18,
    material: "Double sided etch 18 x 24 panel",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 12,
    price: 21.62,
    material: "Double Sided etch/button 12 x 18 panel",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 13,
    price: 30.03,
    material: "Double Sided etch/button 18x24 panel",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 14,
    price: 33.09,
    material: "Three layer etch/button 12 x 18 panel",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 15,
    price: 45.43,
    material: "Three layer etch/button 18x24 panel",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 16,
    price: 7.93,
    material: "Soldermask developing",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 17,
    price: 8.25,
    material: "PLASMA",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 18,
    price: 0.51,
    material: "SOLDERMASK",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 19,
    price: 2.5,
    material: "SILKSCREEN",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 20,
    price: 10,
    material: "ROUTE 10",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 21,
    price: 0.64,
    material: "SILVER SHIELD",
    formula: "price * amount * exchange * 1.2 * size",
    amount: 0,
  },
  {
    id: 22,
    price: 1.24,
    material: "SILVER",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 23,
    price: 3,
    material: "AgCl",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 24,
    price: 17.65,
    material: "HASL (Hot air solder leveling)",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 25,
    price: 70,
    material: "HARD GOLD",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 26,
    price: 17,
    material: "ENIG (Electroless nickel immersion gold )",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 27,
    price: 85,
    material: "ENEPIG (nickel/electroless palladium/gold ) - 12x18",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 28,
    price: 12,
    material: "TEST (12)",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 29,
    price: 5,
    material: "SILVER LABOUR",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 30,
    price: 45,
    material: "VIA FILL - 12x18",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 31,
    price: 80,
    material: "VIA FILL - 18x24",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 32,
    price: 25,
    material: "SCORE (25)",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 33,
    price: 40,
    material: "LABOUR (40)",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 34,
    price: 25,
    material: "DRILL STIFFENER",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 35,
    price: 10,
    material: "PTH STIFFENER",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 36,
    price: 100,
    material: "LASER STIFFENER (PI)",
    formula: "price / 60 * amount * 1.19",
    amount: 0,
  },
  {
    id: 37,
    price: 25,
    material: "ROUTE STIFFENER (FR4)",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 38,
    price: 25,
    material: "ROUTE (Mandatory for rigid flex)",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 39,
    price: 40,
    material: "SCORE (Mandatory for rigid flex)",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 40,
    price: 100,
    material: "LASER TOP COVERLAY",
    formula: "price / 60 * amount * 1.19",
    amount: 0,
  },
  {
    id: 41,
    price: 100,
    material: "LASER BOTTOM COVERLAY",
    formula: "price / 60 * amount * 1.19",
    amount: 0,
  },
  {
    id: 42,
    price: 100,
    material: "LASER MINIPANEL",
    formula: "price / 60 * amount * 1.19",
    amount: 0,
  },
  {
    id: 43,
    price: 100,
    material: "LASER FLEX OUTLINE",
    formula: "price / 60 * amount * 1.19",
    amount: 0,
  },
];
