import { jsonMap } from "Library/Types";

export const dryFilm = [
  {
    id: 1,
    price: 0.22,
    material: "DRY FILM",
    formula: "price * amount * 1.2",
    amount: 0,
  },
  {
    id: 2,
    price: 0.78,
    material: "DRY FILM GOLD",
    formula: "price * amount * 1.2",
    amount: 0,
  },
  {
    id: 222,
    price: 0.56,
    material: "S/M Film",
    formula: "price * amount * 1.06 * 1.2",
    amount: 0,
  },
  {
    id: 3,
    price: 4.71,
    material: "PRESS ",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 4,
    price: 8,
    material: "DRILL",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 5,
    price: 100,
    material: "LASER DRILL",
    formula: "price * amount * 1.19",
    amount: 0,
  },
  {
    id: 6,
    price: 100,
    material: "LASER TOP COVERLAY",
    formula: "price * amount * 1.19",
    amount: 0,
  },
  {
    id: 7,
    price: 100,
    material: "LASER BOTTOM COVERLAY",
    formula: "price * amount * 1.19",
    amount: 0,
  },
  {
    id: 8,
    price: 100,
    material: "LASER MINIPANEL",
    formula: "price * amount * 1.19",
    amount: 0,
  },
  {
    id: 9,
    price: 100,
    material: "LASER FLEX OUTLINE",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 10,
    price: 11.27,
    material: "PTH",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 11,
    price: 8.25,
    material: "PLASMA",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 12,
    price: 0.51,
    material: "SOLDERMASK",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 13,
    price: 2.5,
    material: "SILKSCREEN ",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 14,
    price: 10,
    material: "ROUTE 10",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 16,
    price: 0.58,
    material: "SILVER SHIELD",
    formula: "price * amount * 1.2",
    amount: 0,
  },
  {
    id: 17,
    price: 1.24,
    material: "SILVER",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 18,
    price: 3,
    material: "AgCl",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 19,
    price: 17.65,
    material: "HASL (Hot air solder leveling)",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 20,
    price: 70,
    material: "HARD GOLD",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 21,
    price: 17,
    material: "ENIG (Electroless nickel immersion gold )",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 22,
    price: 85,
    material: "ENEPIG (nickel/electroless palladium/gold ) - 12x18",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 23,
    price: 17.5,
    material: "TEST (17.5)",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 24,
    price: 23,
    material: "TEST (23)",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 26,
    price: 5,
    material: "SILVER LABOUR",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 27,
    price: 40.5,
    material: "VIA FILL - 12x18",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 28,
    price: 77.76,
    material: "VIA FILL - 18x24",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 30,
    price: 25,
    material: "SCORE (25)",
    formula: "price * amount",
    amount: 0,
  },
  {
    id: 34,
    price: 60,
    material: "LABOUR (60)",
    formula: "price * amount",
    amount: 0,
  },
];
