export const services = [
  {
    id: 23,
    service: "Photo Tools",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 24,
    service: "Electrical Test",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 25,
    service: "Outline Die",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 26,
    service: "Secondary Test Fixture",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 27,
    service: "Assyembly Stencils",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 28,
    service: "Assembly Pallets",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 29,
    service: "Design Charge",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 30,
    service: "Production Tooling",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
];
