export const services = [
  {
    id: 16,
    service: "Regular FAI Report",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 17,
    service: "Class 3 documentation",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 18,
    service: "IQ-OQ-PQ ",
    price: 1300,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 19,
    service: "PPAP",
    price: 1300,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 20,
    service: "AS9102",
    price: 350,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 21,
    service:
      "Failure Analysis Report (x-ray, cross-section & electrical verification)",
    price: 500,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 23,
    service: "Photo Tools",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 24,
    service: "Electrical Test",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 25,
    service: "Outline Die",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 26,
    service: "Secondary Test Fixture",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 27,
    service: "Assyembly Stencils",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 28,
    service: "Assembly Pallets",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 29,
    service: "Design Charge",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 30,
    service: "Production Tooling",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
];
