export const services = [
  {
    id: 10,
    material: "SMT Lot Charge",
    price: 675,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 11,
    material: "Stencils (Standard)",
    price: 475,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 12,
    material: "Stencils (Fine Pitch)",
    price: 950,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 13,
    material: "Wood Die",
    price: 750,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 14,
    material: "Chem-Milled",
    price: 1150,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 15,
    material: "Male-Female",
    price: 6000,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 16,
    material: "Regular FAI Report",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 17,
    material: "Class 3 documentation",
    price: 0,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 18,
    material: "IQ-OQ-PQ ",
    price: 1300,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 19,
    material: "PPAP",
    price: 1300,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 20,
    material: "AS9102",
    price: 350,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 21,
    material:
      "Failure Analysis Report (x-ray, cross-section & electrical verification)",
    price: 500,
    amount: 0,
    formula: "price * amount",
  },
  {
    id: 22,
    material: "Finish",
    price: 123,
    amount: 0,
    formula: "price * amount",
  },
];
